=begin Problem 1
Multiples of 3 and 5
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.
The sum of these multiples is 23.  Find the sum of all the multiples of 3 or 5 below 1000.
Solution
=end

# y = 0
# (1..999).each do |x|
# 	y = y + x if (x % 3 == 0) || (x % 5 == 0 )
# end
# puts y


=begin Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
=end

# x = [1,1]
# max = 4_000_000
# seq = x[-1] + x[-2]


# while seq < max
# 	x << seq
# end

# sum = 0

# x.each do |a|
# 	sum += a if a.even?
# end

# puts sum

first = 0
second = 1
max_number = 4000000
seq_num = 0
sum = 0

while seq_num <= max_number
	seq_num = first + second
	sum += seq_num if seq_num % 2 == 0
	first = second
	second = seq_num
end
puts sum

