=begin Problem 1
Multiples of 3 and 5
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.
The sum of these multiples is 23.  Find the sum of all the multiples of 3 or 5 below 1000.
Solution
=end

y = 0
(1..999).each do |x|
	y = y + x if (x % 3 == 0) || (x % 5 == 0 )
end
puts y

puts '-------------------------------------'
=begin Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
=end

first = 0
second = 1
max_number = 4000000
seq_num = 0
sum = 0

while seq_num <= max_number
	seq_num = first + second
	sum += seq_num if seq_num % 2 == 0
	first = second
	second = seq_num
end
puts sum

puts '-------------------------------------'

=begin
Largest prime factor
Problem 3
The prime factors of 13195 are 5, 7, 13 and 29.
What is the largest prime factor of the number 600851475143
=end

max_number = 600_851_475_143
prime_nums = []
x = 2 # this is the first prime number
product_sum = 1

def prime? n
	(2..(n-1)).each do |x|
		if n % x == 0
			return false
		else
			true
		end
	end
end

while product_sum < max_number
	if max_number % x == 0 && prime?(x)
		prime_nums << x
		product_sum *= x
	end
	x += 1
end


puts "the largest prime number for #{max_number} is #{prime_nums.last}"

puts '-------------------------------------'


=begin
Problem 4
A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 * 99.
Find the largest palindrome made from the product of two 3-digit numbers.
=end















puts '-------------------------------------'




























